CREATE DATABASE IF NOT EXISTS sookka
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'sookkaadmin'@'%' IDENTIFIED BY 'sookka123';
GRANT ALL PRIVILEGES ON sookka.* TO 'sookkaadmin'@'%';
FLUSH PRIVILEGES;
