FROM oven/bun:latest

WORKDIR /app

COPY package.json bun.lockb ./
COPY tsconfig.json tsconfig.app.json tsconfig.node.json ./
COPY vite.config.ts ./
COPY tailwind.config.ts ./
COPY postcss.config.js ./
COPY index.html ./
COPY src ./src
COPY public ./public
COPY function ./function

RUN bun install
RUN bun run build

CMD ["bun", "run", "preview", "--", "--host", "0.0.0.0", "--port", "4173"]
